apiVersion : apps/v1
kind: Deployment
metadata:
  name: sunbirdapimanagerutil 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sunbirdapimanagerutil
  template:
    metadata:
      labels:
        app: sunbirdapimanagerutil 
    spec:
      containers:
        - name: sunbirdapimanagerutil 
          image: tesfrt.azurecr.io/sunbirdapimanagerutil
          ports:
          - containerPort: 4000