apiVersion: v1
kind: Service
metadata:
    name: anildesaisunbirdapimanagerutil
spec:
    type: LoadBalancer
    ports:
    - port: 8001 
    selector:
        app: anildesaisunbirdapimanagerutil