apiVersion: v1
kind: Service
metadata:
    name: anildesaisunbirdapimanagerutil
spec:
    type: LoadBalancer
    ports:
    - port: 4000 
    selector:
        app: anildesaisunbirdapimanagerutil